tab_spaces = 2

max_width = 100
chain_width = 90
attr_fn_like_width = 90
fn_call_width = 90
struct_variant_width = 90
array_width = 80
single_line_if_else_max_width = 80
struct_lit_width = 70

comment_width = 100
wrap_comments = true

use_field_init_shorthand = true
use_try_shorthand = true

edition = "2021"
fn_params_layout = "Compressed"
format_code_in_doc_comments = true

match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 16

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true